### PR TITLE
Alternative way to check for One-To-One relationships

### PR DESCRIPTION
**Pull request by danmusk**
Switch from failing when "one of the navigation-props is unknown and the other one is not a collection" (typically one-to-many) to fail when "both is explicitly not a collection" (one-to-one). This seems to fix the problem when the One-side does not have an explicit navigation-property (#1).

### CODE REVIEW

**Comment by danmusk** [comment]
The downside with this approach is that if the one-to-one does not explicitly have a navigation-property on both sides, the SoftDelete will be allowed.

**Comment by JonPSmith** [comment]
Have you got, or can you provide a unit test that fails with the current version of SoftDeleteServices? I want to look into this before I change this.

I'm working so I won't be able to look at this until the weekend.

**Comment by danmusk** [comment]
I do not know if this is the approach you were looking for, but what I did was that I added an optional entity, to the Single-SoftDelete class, `Book.Author` and to the Cascade-SoftDelete class `Customer.Address`. When I revert the if-statement back to the original, some tests now fail with the "one to one can not be SoftDeleted" error. Rolling forward to the alternative if-check all tests pass. There might be some other techniques or features in EF Core that would make it possible to explicitly check for One-to-One, but my knowledge of EF Core is not that good.

**Comment by danmusk** [comment]
Fixed in 1.1.3.

**Pull request closed without merging**
